services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/swifts
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge
