version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app_network
    restart: unless-stopped

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/swifts
    depends_on:
      - mongodb
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge