services:
  mongodb:
    image: mongo:latest  # Używamy oficjalnego obrazu MongoDB
    container_name: mongodb  # Nazwa kontenera
    ports:
      - "27017:27017"  # Mapowanie portu 27017 w kontenerze na port 27017 na hoście
    volumes:
      - mongodb_data:/data/db  # Zabezpieczenie danych w kontenerze
    networks:
      - app_network

  app:
    build: .  # Jeśli masz Dockerfile dla swojej aplikacji
    container_name: app  # Nazwa kontenera dla aplikacji
    ports:
      - "8080:8080"  # Mapowanie portu 8080 w kontenerze na port 8080 na hoście
    environment:
      - MONGO_URI=mongodb://mongodb:27017/swifts  # URI MongoDB do połączenia
    depends_on:
      - mongodb  # Gwarantujemy, że MongoDB będzie działało przed aplikacją
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge
